services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=develop
    depends_on:
      - db

  db:
    image: postgres:16.3-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: playtomic
      POSTGRES_PASSWORD: password
      POSTGRES_DB: playtomic_development

volumes:
  pgdata: