spring.profiles.active: develop
server:
  port: 8090
# Packages to include in swagger doc
springdoc:
  paths-to-exclude: /profile/**, /wallets/**
---
spring.config.activate.on-profile: develop
spring:
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    initialize: false
stripe.simulator.charges-uri: https://sandbox.playtomic.io/v1/stripe-simulator/charges
stripe.simulator.refunds-uri: https://sandbox.playtomic.io/v1/stripe-simulator/payments/{payment_id}/refunds
---
spring.config.activate.on-profile: test
spring:
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    initialize: false
stripe.simulator.charges-uri: http://localhost:${wiremock.server.port}

stripe.simulator.refunds-uri: http://localhost:${wiremock.server.port}
